[package]
name = "ttysvr"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.1.1"
bevy = "0.14.1"
bevy_ratatui = "0.6.1"
bevy_ratatui_render = "0.5.5"
clap = { version = "4.5.13", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
ratatui = "0.27.0"
